game_name: 'StreetsOfRage-Genesis'
tune_path: './results'
tune_num_trials: 100
tune_episode_steps: 10000
tune_env_num: 16
train_path: './model'
train_num_timesteps: 100000000
train_episode_steps: 100000
train_env_num: 16
train_render: True
train_n_stack: 15
train_model_name: 'ppo_cnn_lstm_stack15.zip'
train_record_path: './record'
train_iterations: 200